---
launchpad: oslo.config
team: oslo
type: library
release-model: cycle-with-intermediary
releases:
  - version: 1.5.0
    projects:
      - repo: openstack/oslo.config
        hash: e57aea86c54060d22cc04dd88a4c4feea614d4e4
  - version: 1.6.0
    projects:
      - repo: openstack/oslo.config
        hash: 99e530ed10347fc4c28ff02f3ccdf53c8ed758cf
  - version: 1.6.1
    projects:
      - repo: openstack/oslo.config
        hash: 22413532bfe87bd61e0cc548f6234e6bca36b06b
  - version: 1.7.0
    projects:
      - repo: openstack/oslo.config
        hash: 0abac4881355a395a14a5d68e3347805a480cff9
  - version: 1.8.0
    projects:
      - repo: openstack/oslo.config
        hash: a4abbdbbd7477ef46180c5995fac075678cb7c3a
  - version: 1.9.0
    projects:
      - repo: openstack/oslo.config
        hash: d1ccc438d677c262fa1109f6078c3edc2d59d335
  - version: 1.9.1
    projects:
      - repo: openstack/oslo.config
        hash: 1e42eb8f40eae29dd062d40b53ad37e908d7e72f
  - version: 1.9.2
    projects:
      - repo: openstack/oslo.config
        hash: dc28858f353531444a4f65ffd4330615dd26892a
  - version: 1.9.3
    projects:
      - repo: openstack/oslo.config
        hash: 3c51838cdffe7a5057ff4823a8ab523bfacc3164
repository-settings:
  openstack/oslo.config: {}
