---
launchpad: os-apply-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-apply-config: {}
releases:
  - projects:
      - hash: 7234780bae671b5fead73c00ff4d76221768ccd6
        repo: openstack/os-apply-config
    version: 10.4.0
  - version: 10.4.1
    projects:
      - repo: openstack/os-apply-config
        hash: d9df1dbd367d42430aa9abfe90d5aec572ec152b
  - version: 10.5.0
    projects:
      - repo: openstack/os-apply-config
        hash: 45d999508849137c13eeab63bbec269df232758b
  - version: 10.5.1
    projects:
      - repo: openstack/os-apply-config
        hash: 3c6e3cd638f31bce14344e19ac3ff22d74c0c4af
  - version: 10.5.2
    projects:
      - repo: openstack/os-apply-config
        hash: 6dd7738ea48e7ce8d846ea465e0ddbf1486740c4
  - version: 10.6.0
    projects:
      - repo: openstack/os-apply-config
        hash: 41d86e316ed0f0b9d5c20748b470bff5e6eab73d
branches:
  - name: stable/train
    location: 10.5.0
