---
include-pypi-link: true
launchpad: os-client-config
release-model: cycle-with-intermediary
team: OpenStackSDK
type: library
repository-settings:
  openstack/os-client-config: {}
releases:
  - version: 1.33.0
    projects:
      - repo: openstack/os-client-config
        hash: d0eea17a66e09a1c42e3bb95a384f5a17c9d9072
  - version: train-em
    projects:
      - repo: openstack/os-client-config
        hash: d0eea17a66e09a1c42e3bb95a384f5a17c9d9072
branches:
  - name: stable/train
    location: 1.33.0
release-notes: https://docs.openstack.org/releasenotes/os-client-config/train.html
