---
launchpad: os-collect-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
releases:
  - projects:
      - hash: 8cda3f6cc05ddf714c0b449758b4cf1cc348777a
        repo: openstack/os-collect-config
    version: 10.4.0
  - version: 10.5.0
    projects:
      - repo: openstack/os-collect-config
        hash: 720165e73731ca704a35c6c82ad4a03501f1c712
  - version: 10.5.1
    projects:
      - repo: openstack/os-collect-config
        hash: 0f985b9a658c153627c01810050ccb8d3347392a
  - version: 10.6.0
    projects:
      - repo: openstack/os-collect-config
        hash: 5b8355db34b729733eb420bd970c278b893abf84
branches:
  - name: stable/train
    location: 10.5.0
