---
launchpad: os-net-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-net-config: {}
releases:
  - projects:
      - hash: 115c36b892b6757d0fcf56db6f146a7aed325ccd
        repo: openstack/os-net-config
    version: 11.0.0
  - projects:
      - hash: 564bd19d64b20611b187241fdc27f7c10dc1cbbe
        repo: openstack/os-net-config
    version: 11.1.0
  - version: 11.2.0
    projects:
      - repo: openstack/os-net-config
        hash: a74bbdd7b017fb3bb9faffb4240efa59cb42c79c
  - version: 11.3.0
    projects:
      - repo: openstack/os-net-config
        hash: 2ec6d366ee694e3540eac6ba702e73d9a210c366
  - version: 11.3.1
    projects:
      - repo: openstack/os-net-config
        hash: d814f680410191233f8f857e9f9afa316ce28f72
  - version: 11.4.0
    projects:
      - repo: openstack/os-net-config
        hash: 0cdb1d2aaf176dccde1e4a94cf8668dd48909218
branches:
  - name: stable/train
    location: 11.3.0
release-notes: https://docs.openstack.org/releasenotes/os-net-config/train.html
