---
launchpad: ironic-prometheus-exporter
release-model: cycle-with-intermediary
stable-branch-type: std-with-versions
team: ironic
type: other
repository-settings:
  openstack/ironic-prometheus-exporter: {}
releases:
  - version: 4.7.0
    projects:
      - repo: openstack/ironic-prometheus-exporter
        hash: 6cd0a5a53f3893857c31d01006fcb51102536b7b
