---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 10.1.0
    projects:
      - repo: openstack/oslo.config
        hash: 3146caa10d4dd4e781525ddf78a7b442ac33d8cf
  - version: 10.2.0
    projects:
      - repo: openstack/oslo.config
        hash: 97776b8ebf8a1789768c565dff0ff7555d6ec7b2
