---
launchpad: os-client-config
team: OpenStackClient
type: library
release-model: cycle-with-intermediary
include-pypi-link: yes
release-notes: https://docs.openstack.org/releasenotes/os-client-config/mitaka.html
releases:
  - version: 1.8.0
    projects:
      - repo: openstack/os-client-config
        hash: 1629ae0d1f21dfca0b3f55d23541c61a5a666aca
  - version: 1.8.1
    projects:
      - repo: openstack/os-client-config
        hash: 379962f0e8289e2db85a0eeb7b51d10cff70e67d
  - version: 1.9.0
    projects:
      - repo: openstack/os-client-config
        hash: 790fac98542ba303274180831cbd9a03604a84e8
  - version: 1.10.0
    projects:
      - repo: openstack/os-client-config
        hash: 1b91e007fdeda8703056d50abe431e167afb9e03
  - version: 1.10.1
    projects:
      - repo: openstack/os-client-config
        hash: 13b6fbabeb27a346c91a9fb3a1fb86c7adbd2779
  - version: 1.10.2
    projects:
      - repo: openstack/os-client-config
        hash: 59f719c931771f6fc5372ddde87c4674b3f7cd11
  - version: 1.11.0
    projects:
      - repo: openstack/os-client-config
        hash: 10e96bcb7bed2ca8eaf0185b46dbb882bd8b2b7c
  - version: 1.11.1
    projects:
      - repo: openstack/os-client-config
        hash: 9c59002116e755d9ac7f14b11c3774c6848d4a3c
  - version: 1.12.0
    projects:
      - repo: openstack/os-client-config
        hash: cc92c92870be48d6eae57869c4989125fe2eb8e4
  - version: 1.13.0
    projects:
      - repo: openstack/os-client-config
        hash: 939862e55e42c5fafee9c2fec42b5f5fde8fc205
  - version: 1.13.1
    projects:
      - repo: openstack/os-client-config
        hash: f8c270113579e655fba519a3592a05d982653780
  - version: 1.14.0
    projects:
      - repo: openstack/os-client-config
        hash: 8a6dd7f9bcf94931cbfa7c4acd8920e2cd437e48
  - version: 1.15.0
    projects:
      - repo: openstack/os-client-config
        hash: 7865abc22b7289b2679f6848395d4850d544d1f0
  - version: 1.16.0
    projects:
      - repo: openstack/os-client-config
        hash: 03d5659d8b45b0450a86956147cc2d1f27be66ac
repository-settings:
  openstack/os-client-config: {}
