---
launchpad: oslo.config
team: oslo
type: library
release-model: cycle-with-intermediary
include-pypi-link: yes
release-notes: https://docs.openstack.org/releasenotes/oslo.config/mitaka.html
releases:
  - version: 2.5.0
    projects:
      - repo: openstack/oslo.config
        hash: ddaddba5e5f6499608836b646e6435c15756ec70
  - version: 2.6.0
    projects:
      - repo: openstack/oslo.config
        hash: ee2bab65e9a2f38bb915f106a4da1520e4b5060c
  - version: 2.7.0
    projects:
      - repo: openstack/oslo.config
        hash: 260891bd1ae3b168ba3f9e59c9d68f1a757c0830
  - version: 3.0.0
    projects:
      - repo: openstack/oslo.config
        hash: 9dd719f83aa888efee7f9bcbc8799e86b2ec8504
  - version: 3.1.0
    projects:
      - repo: openstack/oslo.config
        hash: 8cd41466d36a359482f6ed7cc0b1c919541f5461
  - version: 3.2.0
    projects:
      - repo: openstack/oslo.config
        hash: 26eef40f0cc0eba83cab4319667278f9aa741955
  - version: 3.2.1
    projects:
      - repo: openstack/oslo.config
        hash: e2e368bd1dd741c37888a5bba90bdec4de96a888
  - version: 3.3.0
    projects:
      - repo: openstack/oslo.config
        hash: 9db24a4d9a42df27ba7c9dc8afbf9348c7912178
  - version: 3.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 2698e165bd4c0eeb6cb3a28c1d5d44bce75551b7
  - version: 3.5.0
    projects:
      - repo: openstack/oslo.config
        hash: 17a625340a3e044383fbdbe5b256e93a45dc8aab
  - version: 3.6.0
    projects:
      - repo: openstack/oslo.config
        hash: 10215b26e74c71af81752f988b89f15589f2a7f5
  - version: 3.7.0
    projects:
      - repo: openstack/oslo.config
        hash: 1482e5c601d0f75a13972cc808c5fc5a98513624
  - version: 3.8.0
    projects:
      - repo: openstack/oslo.config
        hash: 7bc49da472d2e441bf90b777c55cbe181f5d5f75
  - version: 3.9.0
    projects:
      - repo: openstack/oslo.config
        hash: 77400b2589baec86199b4eb83f12a9dd004bccc9
repository-settings:
  openstack/oslo.config: {}
