---
launchpad: oslo.config
team: oslo
type: library
release-model: cycle-with-intermediary
releases:
  - version: 1.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 059579ac2189b94bc9e9555b2e9acfb31a83ef53
repository-settings:
  openstack/oslo.config: {}
