---
launchpad: os-refresh-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-refresh-config: {}
releases:
  - projects:
      - hash: cf2d98460ddd01f000f2151b98e618b1e13e082c
        repo: openstack/os-refresh-config
    version: 9.0.0
  - projects:
      - hash: a2091f9c65d9d9a22118d0c5cd5ebbe0aab7763b
        repo: openstack/os-refresh-config
    version: 9.1.0
  - projects:
      - hash: a1dad6998dd4cbb1d3cd34afe21cd5923b61e323
        repo: openstack/os-refresh-config
    version: 9.1.1
  - version: rocky-em
    projects:
      - repo: openstack/os-refresh-config
        hash: a1dad6998dd4cbb1d3cd34afe21cd5923b61e323
  - version: rocky-eol
    projects:
      - repo: openstack/os-refresh-config
        hash: 335eac106e7bc243dc1c5576e5ef9e145cb8f7a7
branches:
  - location: 9.1.0
    name: stable/rocky
