---
launchpad: os-collect-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: trailing
repository-settings:
  openstack/os-collect-config: {}
releases:
  - version: 12.0.0
    projects:
      - repo: openstack/os-collect-config
        hash: cc519a7d4844ef7a48ab69abf1d2dd0f90e7bafd
  - version: 12.0.1
    projects:
      - repo: openstack/os-collect-config
        hash: 4e0667fbc620721a79f884854efff835da56a449
  - version: 12.0.2
    projects:
      - repo: openstack/os-collect-config
        hash: 950978bc39785badd96414673cfc5d99a6c24145
branches:
  - name: stable/victoria
    location: 12.0.0
