---
launchpad: os-net-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: trailing
repository-settings:
  openstack/os-net-config: {}
releases:
  - version: 12.4.0
    projects:
      - repo: openstack/os-net-config
        hash: 869d3c13e84c9ccd0944ca8d8854d136c2854f17
  - version: 12.5.0
    projects:
      - repo: openstack/os-net-config
        hash: bca47783bc80999711084eefe499a6a1a9f3628e
  - version: 12.6.0
    projects:
      - repo: openstack/os-net-config
        hash: 933aaf80b14a100b1e5456b82536f8baf62ff01c
  - version: 13.0.0
    projects:
      - repo: openstack/os-net-config
        hash: c01eae0483e69471b564b50d66dc17cd4d793e5f
  - version: 13.1.0
    projects:
      - repo: openstack/os-net-config
        hash: 157df251cf9086cbc58315808ec2f59605626f81
  - version: 13.2.0
    projects:
      - repo: openstack/os-net-config
        hash: 7ba6feaac34a8bc329750bd8cf45c12593428ca8
  - version: 13.2.1
    projects:
      - repo: openstack/os-net-config
        hash: 2fcf8b04cf8b2074e4e900ccba4e07bb28bd3fe0
branches:
  - name: stable/victoria
    location: 13.0.0
