---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 8.6.0
    projects:
      - repo: openstack/oslo.config
        hash: 6e91dbb2d590fc1706243922c0ed71f6c2fcdf73
  - version: 8.7.0
    projects:
      - repo: openstack/oslo.config
        hash: d8cf65ddc9b662c48c408d3bf34c28b7a7594694
