---
launchpad: os-collect-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: trailing
repository-settings:
  openstack/os-collect-config: {}
releases:
  - version: 11.0.0
    projects:
      - repo: openstack/os-collect-config
        hash: 0558b20f5a4f2508afc355abe76d1c825bf17592
  - version: 11.0.1
    projects:
      - repo: openstack/os-collect-config
        hash: 24245ce18ea0c1bbb2be901d638e90fe935bba1c
  - version: 11.0.2
    projects:
      - repo: openstack/os-collect-config
        hash: cc519a7d4844ef7a48ab69abf1d2dd0f90e7bafd
  - version: 11.0.3
    projects:
      - repo: openstack/os-collect-config
        hash: 5939eab15fe5275cb3620c5997a82dd1b7c6933d
branches:
  - name: stable/ussuri
    location: 11.0.2
