---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 6.12.0
    projects:
      - repo: openstack/oslo.config
        hash: f0c992f5c088054196389ab12599e52ec5970d3a
  - version: 7.0.0
    projects:
      - repo: openstack/oslo.config
        hash: edcb46deae997056020acff8d24bf328778624c9
  - version: 8.0.0
    projects:
      - repo: openstack/oslo.config
        hash: 4e071eb034eae728cef397c2c37334dd2c8c9251
  - version: 8.0.1
    projects:
      - repo: openstack/oslo.config
        hash: c4a4d39e1109f0e97ae7e4231e5a1a682946e8c9
  - version: 8.0.2
    projects:
      - repo: openstack/oslo.config
        hash: d93bfe182e46837e0f90a3bb2e73aa3aeec8fdc9
  - version: 8.0.3
    projects:
      - repo: openstack/oslo.config
        hash: acb54b9ffb818ba49f11e6ebac331621cbc8fc81
branches:
  - name: stable/ussuri
    location: 8.0.2
release-notes: https://docs.openstack.org/releasenotes/oslo.config/ussuri.html
