---
branches:
  - location: 6.0.0.0rc1
    name: stable/ocata
launchpad: os-collect-config
release-model: cycle-with-milestones
releases:
  - projects:
      - hash: e8e2f3d5f2ebc6c08383bf98e5e27c689fc6e7a1
        repo: openstack/os-collect-config
    version: 6.0.0.0b1
  - projects:
      - hash: bf7cc362d3928aedc2b48f1ffe871436b47b9483
        repo: openstack/os-collect-config
    version: 6.0.0.0b2
  - projects:
      - hash: cb846967f7d8e1f0a14f53e747ea5623e0a559d8
        repo: openstack/os-collect-config
    version: 6.0.0.0rc1
  - diff-start: 5.0.0
    projects:
      - hash: cb846967f7d8e1f0a14f53e747ea5623e0a559d8
        repo: openstack/os-collect-config
    version: 6.0.0
  - projects:
      - hash: 386cedabf7f38e2f8324b31d566de45457a5a04f
        repo: openstack/os-collect-config
    version: 6.1.0
team: tripleo
type: other
