---
launchpad: os-cloud-config
team: tripleo
type: other
release-model: cycle-with-milestones
artifact-link-mode: none
branches:
  - name: stable/newton
    location: 5.0.0
releases:
  - version: 5.0.0.0b1
    projects:
      - repo: openstack/os-cloud-config
        hash: becaec5476e5889e0174c6ac65606173a71dbe9a
  - version: 5.0.0.0b2
    projects:
      - repo: openstack/os-cloud-config
        hash: 7bf38a33be8daae723c87db5d4702f53adcd1a9d
  - version: 5.0.0.0b3
    projects:
      - repo: openstack/os-cloud-config
        hash: e1dca0031edf88b8c5272c4e739b02dd5d6c8e83
  - version: 5.0.0
    diff-start: 0.4.1
    projects:
      - repo: openstack/os-cloud-config
        hash: e1dca0031edf88b8c5272c4e739b02dd5d6c8e83
  - version: 5.1.0
    projects:
      - repo: openstack/os-cloud-config
        hash: 6ff20281fe802a001bcabbc719db7e49e42592f7
