---
launchpad: os-apply-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-apply-config: {}
releases:
  - projects:
      - hash: 21be52c835180cbe138acbfde4e6ec344ded634e
        repo: openstack/os-apply-config
    version: 10.0.0
  - projects:
      - hash: 6543fc7498fe3a8dd961a3d755237a3289ae1fc1
        repo: openstack/os-apply-config
    version: 10.1.0
  - projects:
      - hash: b7a2d9e46cac43311a3410902cb74292b0395a05
        repo: openstack/os-apply-config
    version: 10.2.0
  - projects:
      - hash: 9a50e081cb9bc27ec573bda5ad00beff64b23dec
        repo: openstack/os-apply-config
    version: 10.3.0
  - version: stein-em
    projects:
      - repo: openstack/os-apply-config
        hash: 9a50e081cb9bc27ec573bda5ad00beff64b23dec
branches:
  - location: 10.3.0
    name: stable/stein
