---
launchpad: os-net-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-net-config: {}
releases:
  - projects:
      - hash: f73505895bc438546d44e8b4853a10a516696b87
        repo: openstack/os-net-config
    version: 10.0.0
  - projects:
      - hash: a34e5b7cc1500694e0ac0a39dbcd506f2e446b87
        repo: openstack/os-net-config
    version: 10.1.0
  - projects:
      - hash: 0607a2ac29a342b399b087be7d2f3ce3a8b5d429
        repo: openstack/os-net-config
    version: 10.2.0
  - projects:
      - hash: e912b02c3bec61ec3af610820601cc24b5dc1cba
        repo: openstack/os-net-config
    version: 10.3.0
  - projects:
      - hash: b82730235eb3e0ffddf12e12a2ffd85f52984c0c
        repo: openstack/os-net-config
    version: 10.4.0
  - version: 10.4.1
    projects:
      - repo: openstack/os-net-config
        hash: 14e46a5accc1501ed2f599d65eff069afb505c8b
  - version: 10.4.2
    projects:
      - repo: openstack/os-net-config
        hash: ab7364accb8b2198ec4718e2aeb5009af2c108bb
  - version: stein-em
    projects:
      - repo: openstack/os-net-config
        hash: ab7364accb8b2198ec4718e2aeb5009af2c108bb
branches:
  - location: 10.4.0
    name: stable/stein
release-notes: https://docs.openstack.org/releasenotes/os-net-config/stein.html
