---
launchpad: os-refresh-config
release-model: cycle-trailing
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-refresh-config: {}
releases:
  - projects:
      - hash: 2cdebc64e0a3b3064cc472c08cbede138497839d
        repo: openstack/os-refresh-config
    version: 10.0.0
  - projects:
      - hash: 4e9ce62c04eb13850fb40552033362464171255b
        repo: openstack/os-refresh-config
    version: 10.1.0
  - projects:
      - hash: d0277ff94839b636b013de8263debf285217b10a
        repo: openstack/os-refresh-config
    version: 10.2.0
  - version: 10.2.1
    projects:
      - repo: openstack/os-refresh-config
        hash: 8328f6531b2a30c31add74297e57c36deb09aff8
  - version: 10.2.2
    projects:
      - repo: openstack/os-refresh-config
        hash: 2c77834219fe86218a22f6cc07f8708321b5b00b
  - version: stein-em
    projects:
      - repo: openstack/os-refresh-config
        hash: 2c77834219fe86218a22f6cc07f8708321b5b00b
branches:
  - location: 10.2.0
    name: stable/stein
