---
team: OpenStackAnsible
type: other
launchpad: openstack-ansible
release-notes: https://docs.openstack.org/releasenotes/ansible-config_template/
releases:
  - version: 1.0.0
    projects:
      - repo: openstack/ansible-config_template
        hash: 937d9956e601e4cb41cb9d057e4312097dfec414
  - version: 1.1.0
    projects:
      - repo: openstack/ansible-config_template
        hash: 84fd42f56f9554ffc1a4f7574469fe6ca34a4a1a
  - version: 1.1.1
    projects:
      - repo: openstack/ansible-config_template
        hash: 4ed672e3992f41dc4020ba68b8ea12d657a11710
repository-settings:
  openstack/ansible-config_template:
    flags:
      - no-artifact-build-job
