---
launchpad: eslint-config-openstack
team: 'Quality Assurance'
type: other
include-pypi-link: false
releases:
  - version: 1.2.0
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 20b818fbf3e2561ebb7da518460ef98cfd860844
  - version: 1.2.1
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 835416849ec9ea9e5696745e5defbf0ca90ce44a
  - version: 1.2.2
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 2c5d458d935b6e96d98a5656386a9f680bccff49
  - version: 1.2.3
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 36d8d9deb98c1da41c0f3b94a1bcb88a2a26b872
  - version: 1.2.4
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 9f4fcab83874420cd4e2d757601c9faea2aef102
  - version: 2.0.0
    projects:
      - repo: openstack/eslint-config-openstack
        hash: be774d754dbc6032839e96b72f24c471d66088c5
  - version: 4.0.0
    projects:
      - repo: openstack/eslint-config-openstack
        hash: adb1c12b37a9be498094808632cdd49aec0a0570
  - version: 4.0.1
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 4549ae61e2ed19659c3d641ebd37ebdf12eb4d7f
  - version: 4.1.0
    projects:
      - repo: openstack/eslint-config-openstack
        hash: 3c9bc333ed891e4a4a9549aa5723f4c0f23168b9
repository-settings:
  openstack/eslint-config-openstack: {}
