---
launchpad: os-apply-config
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-apply-config: {}
releases:
  - version: 13.0.0
    projects:
      - repo: openstack/os-apply-config
        hash: 2bf86c4c82404d3e987be23cf85f270a3c46c6e0
  - version: 13.0.1
    projects:
      - repo: openstack/os-apply-config
        hash: 891e996920345c72e4b2d5f6c28c4f049225f0a4
