---
launchpad: os-collect-config
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-collect-config: {}
releases:
  - version: 0.1.34
    projects:
      - repo: openstack/os-collect-config
        hash: eefebd7682a9b871128292105175bc29f5e18a9d
  - version: 0.1.35
    projects:
      - repo: openstack/os-collect-config
        hash: 163030c08181ef152ea8bb80ea88dfe0dfe519eb
  - version: 13.0.0
    projects:
      - repo: openstack/os-collect-config
        hash: cc519a7d4844ef7a48ab69abf1d2dd0f90e7bafd
  - version: 13.0.1
    projects:
      - repo: openstack/os-collect-config
        hash: 224af052afd3ee59911dc8809ad6758983a95884
