---
launchpad: os-collect-config
team: tripleo
type: other
releases:
  - version: 0.1.34
    projects:
      - repo: openstack/os-collect-config
        hash: eefebd7682a9b871128292105175bc29f5e18a9d
  - version: 0.1.35
    projects:
      - repo: openstack/os-collect-config
        hash: 163030c08181ef152ea8bb80ea88dfe0dfe519eb
repository-settings:
  openstack/os-collect-config: {}
