---
launchpad: os-net-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: trailing
repository-settings:
  openstack/os-net-config: {}
releases:
  - version: 14.0.0
    projects:
      - repo: openstack/os-net-config
        hash: 84a1a5222d58dc7602e4674132c81dd010d8c5b1
  - version: 14.1.0
    projects:
      - repo: openstack/os-net-config
        hash: 012b58ccc1623945c4428e82eec80b2f3f22d6b7
branches:
  - name: stable/wallaby
    location: 14.1.0
