---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 8.4.0
    projects:
      - repo: openstack/oslo.config
        hash: efa46b5f441ed377a777f33b66aa4070ae133c9f
  - version: 8.5.0
    projects:
      - repo: openstack/oslo.config
        hash: cfa256464e519468f227e676e2ca0829bf5c7e02
  - version: 8.5.1
    projects:
      - repo: openstack/oslo.config
        hash: de1dbeed235d2df7cf1528aef6ad4a70ddf8559f
  - version: wallaby-em
    projects:
      - repo: openstack/oslo.config
        hash: de1dbeed235d2df7cf1528aef6ad4a70ddf8559f
  - version: wallaby-eom
    projects:
      - repo: openstack/oslo.config
        hash: 03a2344d8de0c213f6b3453b5d357a53d6b313d4
  - version: wallaby-eol
    projects:
      - repo: openstack/oslo.config
        hash: 98a4ab6420b1dae77beaf499e26c190916353845
branches:
  - name: stable/wallaby
    location: 8.5.0
  - name: unmaintained/wallaby
    location: wallaby-eom
release-notes:
  https://docs.openstack.org/releasenotes/oslo.config/wallaby.html
