---
launchpad: os-client-config
team: OpenStackClient
type: library
release-model: cycle-with-intermediary
releases:
  - version: 0.8.1
    projects:
      - repo: openstack/os-client-config
        hash: 3f8431a9de68b9e2fa24237f51d5497ca5da0295
  - version: 0.8.2
    projects:
      - repo: openstack/os-client-config
        hash: aefb164f9b3693666cd8eed6fbd3261a7c959c24
  - version: 1.0.0
    projects:
      - repo: openstack/os-client-config
        hash: fa941945bed1a52995638a257b45a56a4937914c
  - version: 1.1.0
    projects:
      - repo: openstack/os-client-config
        hash: 2580c0aa0112d94606879c8f8864e34602ddaab8
  - version: 1.2.0
    projects:
      - repo: openstack/os-client-config
        hash: daab3615e2884100f88a797570c1326c8139983c
  - version: 1.3.0
    projects:
      - repo: openstack/os-client-config
        hash: a0df67704ace186b18fd1ecdc220a7e56409bc6f
  - version: 1.4.0
    projects:
      - repo: openstack/os-client-config
        hash: c66eaec73dcc2171fa733300242391a812885144
  - version: 1.5.0
    projects:
      - repo: openstack/os-client-config
        hash: f3e12a68fc00bf231dc4fce3279533d9050c9e11
  - version: 1.6.0
    projects:
      - repo: openstack/os-client-config
        hash: 0567c717162f6a5643d15b526aa68d3b3eadb5ce
  - version: 1.6.1
    projects:
      - repo: openstack/os-client-config
        hash: a8e8c809eeec0f09b5d9207c29efb3c6a1f9c088
  - version: 1.6.2
    projects:
      - repo: openstack/os-client-config
        hash: a2be4a78c89e66758aea9280e14e0455daa3de82
  - version: 1.6.3
    projects:
      - repo: openstack/os-client-config
        hash: c422fe89ab6e13dcb10fdc26a6b5369b22901af7
  - version: 1.6.4
    projects:
      - repo: openstack/os-client-config
        hash: 3f76cc5fa9d288b25b3804966568b8bd900a54c1
  - version: 1.7.0
    projects:
      - repo: openstack/os-client-config
        hash: 4287c75c5795665e2a7dfdbab826adbc1a106df4
  - version: 1.7.1
    projects:
      - repo: openstack/os-client-config
        hash: 64d3393a620d87634e2a4bb0afb15eb815641421
  - version: 1.7.2
    projects:
      - repo: openstack/os-client-config
        hash: 21bb2f347d0d52defa98726b7102c1853b558072
  - version: 1.7.3
    projects:
      - repo: openstack/os-client-config
        hash: 8317c2bf7929cb881721c862d3c5e18d95e1aa2d
  - version: 1.7.4
    projects:
      - repo: openstack/os-client-config
        hash: 8dee656df809ed1b39b2800e35cc5ef67c31e84e
  - version: 1.7.5
    projects:
      - repo: openstack/os-client-config
        hash: 512d00e208190cd3d38ff275567633ff1dcdcf20
repository-settings:
  openstack/os-client-config: {}
