---
launchpad: oslo.config
team: oslo
type: library
release-model: cycle-with-intermediary
releases:
  - version: 1.10.0
    projects:
      - repo: openstack/oslo.config
        hash: 3ab403925e9cb2928ba8e893c4d0f4a6f4b27d72
  - version: 1.11.0
    projects:
      - repo: openstack/oslo.config
        hash: 2e32e5863f7849b00610f7bac82746fb5604851e
  - version: 1.12.0
    projects:
      - repo: openstack/oslo.config
        hash: 02a86d2eefeda5144ea8c39657aed24b8b0c9a39
  - version: 1.12.1
    projects:
      - repo: openstack/oslo.config
        hash: 0c9113f68285f7b55ca01f0bbb5ce6cddada5023
  - version: 1.13.0
    projects:
      - repo: openstack/oslo.config
        hash: 56073f066d38aa3dba0e83b66c931d745fa40155
  - version: 1.14.0
    projects:
      - repo: openstack/oslo.config
        hash: ac7c55dee3d5b27d45ab31456d5182902c95164b
  - version: 1.15.0
    projects:
      - repo: openstack/oslo.config
        hash: cbf6b30a7bbbb82d3123fa7e7f3494fd916f404c
  - version: 2.0.0
    projects:
      - repo: openstack/oslo.config
        hash: 1dad55fbe2d1a80f6341f749d6f8f55ecfd33104
  - version: 2.1.0
    projects:
      - repo: openstack/oslo.config
        hash: ac505d83e4eeb7f4d0e813e4b33cf97d2d1613a2
  - version: 2.2.0
    projects:
      - repo: openstack/oslo.config
        hash: a91cfb5966108dfc6461290a1df0da5d7865e892
  - version: 2.3.0
    projects:
      - repo: openstack/oslo.config
        hash: bc13758bd6a12f3a9be0d4f6ecfe3d2785df543a
  - version: 2.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 7a9f4e7d670d5e74af85fd28edd898babc9d230b
repository-settings:
  openstack/oslo.config: {}
